New commit system

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,17 +1,24 @@
 #!/bin/bash
-set -e
 
-function echoErrorMessage () {
-  echo << EOM
-Warning, you have uncommitted changes!
-Perhaps you forgot to `git add` after linter?
+
+if git status --porcelain=v1 | grep MM > /dev/null ; then
+  cat << EOM
+
+Warning, you have double-modified uncommitted changes (above)!
+Perhaps you forgot to "git add" after linter?
+
 If you're working on multiple changes at a time, you can:
-  - `git stash push /path/to/file` to stash just some changes
+  - "git stash push /path/to/file" to stash just some changes
   - make a separate branch with some of your changes only.
 EOM
-}
+  exit 1
+fi
 
-[ ! -z "$(git diff)" ] && echoErrorMessage && exit 1;
+
+if ! (git status --porcelain=v1 | cut -c 1 | grep -e "[DAM]" > /dev/null) ; then
+  echo "No changes to commit, abort."
+  exit 1
+fi
 
 npm run lint 
 npm run test
